apiVersion: batch/v1
kind: CronJob
metadata:
  name: kube-ecrlogin
spec:
  schedule: "0 */4 * * *"
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sidecar
            image: docker.io/levilutz/kube-ecrlogin-sidecar:97c3bb18319b78bf11efae2cc0e78f3ad47290a6
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
            lifecycle:
              postStart:
                exec:
                  command:
                  - /wait_until_ready.sh
          - name: main
            image: docker.io/levilutz/kube-ecrlogin-main:97c3bb18319b78bf11efae2cc0e78f3ad47290a6
            imagePullPolicy: Always
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: kube-ecrlogin-aws
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: kube-ecrlogin-aws
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: kube-ecrlogin-aws
                  key: AWS_DEFAULT_REGION
            - name: AWS_ECR_SERVER
              valueFrom:
                secretKeyRef:
                  name: kube-ecrlogin-aws
                  key: AWS_ECR_SERVER
          restartPolicy: OnFailure
