apiVersion: batch/v1
kind: CronJob
metadata:
  name: kube-ecr-login
spec:
  schedule: "0 */4 * * *"
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sidecar
            image: docker.io/levilutz/kube-ecr-login:latest-sidecar
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
            lifecycle:
              postStart:
                exec:
                  command:
                  - /wait_until_ready.sh
          - name: main
            image: docker.io/levilutz/kube-ecr-login:latest-main
            imagePullPolicy: Always
            env:
            - name: AWS_ACCESS_KEY_ID
              value: "YOUR AWS_ACCESS_KEY_ID"
            - name: AWS_SECRET_ACCESS_KEY
              value: "YOUR AWS_SECRET_ACCESS_KEY"
            - name: AWS_DEFAULT_REGION
              value: "YOUR AWS_DEFAULT_REGION"
            - name: AWS_ECR_SERVER
              value: "YOUR AWS_ECR_SERVER"
          restartPolicy: OnFailure
