name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Main
        run: ./build_main.sh

      - name: Build Sidecar
        run: ./build_sidecar.sh

      - name: Login to Docker Hub
        run: |
          buildah login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_SERVER }}

      - name: Push Main
        run: |
          repo=${{ secrets.DOCKER_SERVER }}/kube-ecrlogin-main
          buildah tag kube-ecrlogin-main $repo:$GITHUB_SHA
          buildah push $repo:$GITHUB_SHA

      - name: Push Main, Tag latest
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          repo=${{ secrets.DOCKER_SERVER }}/kube-ecrlogin-main
          buildah tag kube-ecrlogin-main $repo:latest
          buildah push $repo:latest

      - name: Push Sidecar
        run: |
          repo=${{ secrets.DOCKER_SERVER }}/kube-ecrlogin-sidecar
          buildah tag kube-ecrlogin-sidecar $repo:$GITHUB_SHA
          buildah push $repo:$GITHUB_SHA

      - name: Push Sidecar, Tag latest
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          repo=${{ secrets.DOCKER_SERVER }}/kube-ecrlogin-sidecar
          buildah tag kube-ecrlogin-sidecar $repo:latest
          buildah push $repo:latest
